### ISSUE TITLE
Updates in the DAPS

### ISSUE THREAD

**Issue by aitorce** [International-Data-Spaces-Association/omejdn-daps#1]
I have installed the latest DAPS version as I have seen changes in the last couple of weeks and I am having issues obtaining a DAT through the "create_test_token.rb" script. I have copied the same changes I performed in a previous DAPS version, but it is not working as expected.

The copy I currently have was called v0.0.2 when this repo showed the version. The working version was downloaded in the beginning of the month and the new version was downloaded last week as of this post.

I have taken screenshots below regarding the working version in the LEFT and the non-working version on the RIGHT.

config/clients.yml:
![image](https://user-images.githubusercontent.com/82808687/138685891-fb1e0f7e-6001-47bd-8741-0da6e9923fea.png)

config/omejdn.yml. The DAPS in the right also has "user_backend". It is not shown here because it was not altered in any way. It also has "user_selfservice":
![image](https://user-images.githubusercontent.com/82808687/138684879-4ae707ed-0942-4a46-aed1-1938a272dabd.png)

keys/:
![image](https://user-images.githubusercontent.com/82808687/138685232-7fcc16d2-bbcb-4bcc-82b1-cc643d6dc4b2.png)

scripts:
![image](https://user-images.githubusercontent.com/82808687/138685454-8b2696e6-9cb2-40ee-b810-0a0d0d504d26.png)

scripts/create_test_token.rb:
![image](https://user-images.githubusercontent.com/82808687/138680053-421f1e47-ca1c-4c2a-a1f2-2886846e00d9.png)

Response from the "old" DAPS:
![image](https://user-images.githubusercontent.com/82808687/138682504-10c71117-051b-401b-8325-a2fbb900b36d.png)

Response from the "new" DAPS:
![image](https://user-images.githubusercontent.com/82808687/138682563-3724fcd4-68db-4b19-b479-0d3840143151.png)

Is there anything I may be missing? It was not working, so I copied the old setup and it still will not work.

Is it an option to keep having versions as to avoid this in the future? Instead of "old" vs "new", have a v0.0.2 vs v0.0.3.

**Comment by bellebaum** [comment]
Did that fix the issue?

**Comment by bellebaum** [comment]
Closing this issue due to a lack of further information.
Feel free to reopen it should the problem persist.
