### ISSUE TITLE
JWKS url of  DAPS

### ISSUE THREAD

**Issue by arnabghosh3654** [International-Data-Spaces-Association/omejdn-daps#10]
Is there a public JWKS URL for this DAPS server? I want to use some Data Connectors in PRODUCTION_DEPLOYMENT mode with this DAPS server. For that, I would need to add the public JWKS URL of this DAPS to the application properties of the connector.

**Comment by schanzen** [comment]
Yes, you can either get the info from the metadata at `https://YOUR_DOMAIN/.well-known/openid-configuration` or directly at `https://YOUR_DOMAIN/.well-known/jwks.json`

**Comment by arnabghosh3654** [comment]
Thanks!
