### ISSUE TITLE
Problem with docker with the daps

### ISSUE THREAD

**Issue by aetxeberriasqs** [International-Data-Spaces-Association/omejdn-daps#12]
I have followed the README ont the https://github.com/International-Data-Spaces-Association/omejdn-daps page, and fully executed it, yet i have not found in the documentation the link or the mention that the DAPS can be executed with dockers nor the link to https://github.com/Fraunhofer-AISEC/omejdn-server/tree/cb6d5e56c98b07d70d6753e32901d65df785fcf3, althougt there is a link in with the other folders. 

It is not correctly stated that it can be installed using dockers, nor the link to the fraunhofer page. With the code i downloaded in the omejdn-daps page, https://github.com/International-Data-Spaces-Association/omejdn-daps I have tried to execute the steps shown in the fraunhofer page and I have found some error. 

>sqs@Virtual-Ubuntu-20:~/DAPS-DOCKER/omejdn-daps/omejdn-server$ docker run -d --name=omejdn -p 4567:4567 -v $PWD/config:/opt/config -v $PWD/keys:opt/keys my-omjdn-server
docker: Error response from daemon: invalid volume specification: '/home/sqs/DAPS-DOCKER/omejdn-daps/omejdn-server/keys:opt/keys': invalid mount config for type "bind": invalid mount path: 'opt/keys' mount path must be absolute.
See 'docker run --help'.

Could the documentation be changed so that both ways can be done? and what problem could it be  in this step using dockers?

**Comment by bellebaum** [comment]
Thanks for your issue.

> what problem could it be in this step using dockers?

>> 'opt/keys' mount path must be absolute.

Exactly this. Absolute paths start with `/`.

> Could the documentation be changed so that both ways can be done?

In theory, yes. And I probably will add a note at some point.
Although I should note that the README in this repository is only intended to get people going for simple test setups, not for production use.
If one needs to use infrastructure involving docker their usecase likely should entail securing certain aspects of Omejdn not covered in the README. A few issues and recommendations are mentioned in the section `Going forward`.

Note that the README does not go into a lot of details for the necessary steps, as this kind of configuration is targeted at experienced server administrators.

**Comment by bellebaum** [comment]
Due to inactivity, I will assume the problem to be resolved and close this issue.
Feel free to reopen, should the problem persist
