### ISSUE TITLE
Error: access_denied

### ISSUE THREAD

**Issue by aitorcelaya** [International-Data-Spaces-Association/omejdn-daps#14]
I have installed the latest version of the DAPS and I am having issues with the `create_test_token.rb` script. 

I have successfully updated the `clients.yml` and `omejdn.yml` files. I have added my .cert file in `keys` and I was able to able to obtain a client_assertion. 

I get the following error:
![image](https://user-images.githubusercontent.com/82808687/146758403-c8998b06-1668-4c78-bc23-ebbe52ad4fd7.png)

I have not had this "access_denied" issue before and the "error_description" seems to be empty.

What does this error mean so that I can obtain a valid DAT?

**Comment by bellebaum** [comment]
Thanks for your issue.
Have you tried to run the `test.sh` script in `scripts` (not `omejdn-server/scripts`)?
How exactly were you using the `create_test_token.rb` script?

**Comment by aitorcelaya** [comment]
Thank you @bellebaum.
A colleague was able to solve the same issue in https://github.com/International-Data-Spaces-Association/omejdn-daps/issues/15.

Issue can be closed.
