### ISSUE TITLE
Documentation change request

### ISSUE THREAD

**Issue by aetxeberriasqs** [International-Data-Spaces-Association/omejdn-daps#16]
Hi,

I have followed the instructions to deploy the DAPS with the documentation in the https://github.com/International-Data-Spaces-Association/omejdn-daps with the recommended configuration and with dockers using the commands at https://github.com/Fraunhofer-AISEC/omejdn-server. 

But as for the evaluation documentation, this information is not well structured and it is confusing, as in some points the user have to change between the different pages and documentation and it is not clear when it starts one and one you have to change to another. All the documentation regarding the DAPS should be included in https://github.com/International-Data-Spaces-Association/omejdn-daps and it should be consecuent and follow a path to the deployment, let it be with bundle or dockers.

It also should include what type of changes should be done in the documentation, for example, when using create_test_token.rb, it does not specify where the connectors key should be relocated, or what are the arguments of the create test token command. It should also state if the ruby needs an actualitation, and what is the command for that or what is the command for installing jq for JSON or the correct curl command for retrieving the DAT.

**Comment by bellebaum** [comment]
To add some context, and to clarify the purpose of this repository:

The functionality of a DAPS is specified in the [IDS-RAM](https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0) and, more concretely, the [IDS-G](https://github.com/International-Data-Spaces-Association/IDS-G). This functionality can be achieved by several pieces of software, one of which - *but not the only one* - is the [Omejdn OAuth Server](https://github.com/Fraunhofer-AISEC/omejdn-server).

In general, IDS Actors wishing to operate their own DAPS are expected to know the specifications and handling of their chosen OAuth Server, be that by their own research or by contract with an external partner, to implement the DAPS functionality.

We recognize that not every actor, and researcher in particular, has the required expertise in every part of the IDS ecosystem. Hence this repository provides a bare minimum of configuration necessary for test setups.

In particular, extensions necessary for production (like TLS) and particular setups (like involving containers) are not covered by this documentation, and at best mentioned as a reminder to those wishing to properly set up a production-ready DAPS.

---

About your request:
I would rather not add another alternative setup description just for using Docker. If you like, feel free to add a Wiki page to which the README could link.

**Comment by bellebaum** [comment]
I switched the main documentation to Docker now. Closing.
