### ISSUE TITLE
production certs don't match

### ISSUE THREAD

**Issue by spetrac** [International-Data-Spaces-Association/omejdn-daps#26]
There seem to be an error with the production certs.

The nginx config requires the certs to be named as `omejdn.cert` and `omejdn.key`:

https://github.com/International-Data-Spaces-Association/omejdn-daps/blob/f7f097234fdd0f32a2f9781e5d575b4fc544350a/nginx.production.conf#L6-L7

But the compose volume maps the tls config to `daps.cert` and `daps.key`:

https://github.com/International-Data-Spaces-Association/omejdn-daps/blob/f7f097234fdd0f32a2f9781e5d575b4fc544350a/compose.yml#L15-L16

**Comment by bellebaum** [comment]
I have fixed it. Thanks for spotting and reporting :)
