### ISSUE TITLE
Gemfile not available in DAPS

### ISSUE THREAD

**Issue by aetxeberriasqs** [International-Data-Spaces-Association/omejdn-daps#4]
I have followed the installation guide and in the section of documentation starting Omejdn I have found the following issue with the command bundle install:

Could not locate Gemfile 

![image](https://user-images.githubusercontent.com/91265606/140913907-87960ed6-4d91-4ae7-9a8f-4257cb2a15ca.png)

What are the steps needed to execute correctly the bundle install? Where can I find this Gemfile?

Thanks in advance

**Comment by bellebaum** [comment]
Thanks for your issue. Have you read the section on `Requirements` and initialized the submodules using the following command?

```
$ git submodules update --init --remote
```

**Comment by aetxeberriasqs** [comment]
Hi,

I have tried $ git submodule update --init --remote  (without S )in the omejdn-daps folder, as any other combination or other directory made an error. 
Once i have that, the bundle install command keep saying that it could not locate Gemfile

![image](https://user-images.githubusercontent.com/91265606/140929365-98e022be-903f-48b0-8c01-9ee4754496fe.png)

Is there anything i am missing here?

Thanks

**Comment by bellebaum** [comment]
Without `s`, but still `--remote` instead of `--resource` ;)
Just in case, you should also remove everything inside `omejdn-server`, then run this command and afterwards copy the files again according to the README

**Comment by bellebaum** [comment]
and yes, inside the `omejdn-daps` folder

**Comment by aetxeberriasqs** [comment]
Thanks! 

It seems i was inserting something wrong. I am looking at the README again, and when starting the omejdn, it says the folders key and config should be preplaced. I am guessing that the key and config folders that must be replaced are the ones that arer in the omejdn-server for the one that are in the omejdn-daps?

**Comment by bellebaum** [comment]
Correct, Omejdn-Server comes with its own default configuration, but for usage as a DAPS you need the files listed (and generated throughout the README) in this repository.

For now, I am closing this issue as the original problem seems to be resolved
