### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by dadebuch** [International-Data-Spaces-Association/omejdn-daps#6]
# The Problem
The connector fetches a token but then throws a javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

## My Setup

I'm running two connectors instances in a docker compose environment as well as a DAPS instance. I followed the configuration steps to create a daps certificate and key. I also created self signed certificates with the Register_connector.sh script and configured a keystore/truststore. (Without using the DAPS in TEST_DEPLOYMENT the TLS connection works fine). I tried to add the DAPS certificate in both the connectors truststores but the error won't change.

![SSL_Error](https://user-images.githubusercontent.com/34966289/141083564-82feb654-c48e-4313-8bd0-c030dde6baa3.JPG)

The DAPS token is correctly fetched but an error occurs in my opinion when the connector tries to verify it? the screen does not shows the detected causes:

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Thanks for any response.

**Comment by bellebaum** [comment]
If the DAT was sucessfully issued, this is likely a problem with the Connector. Transferring...

**Comment by bellebaum** [comment]
For some reason, GitHub won't let me transfer this. Please file an issue at https://github.com/International-Data-Spaces-Association/DataspaceConnector

**Comment by dadebuch** [comment]
Oh ok, thank you :)
